name: Action

on:
  push:
    tags:
      - "v*"

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v

      - name: Change
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"